server {
    listen 3002;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location ^~ /candidatos/ {
        alias /var/www/candidatos/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
        access_log off;
    }

    location = /index.html {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires "0";
    }

    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}
