/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComitesRouteImport } from './routes/comites'
import { Route as MateriaisRouteImport } from './routes/materiais'
import { Route as PessoasRouteImport } from './routes/pessoas'
import { Route as SaidasIndexRouteImport } from './routes/saidas.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComitesRoute = ComitesRouteImport.update({
  id: '/comites',
  path: '/comites',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriaisRoute = MateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => rootRouteImport,
} as any)
const PessoasRoute = PessoasRouteImport.update({
  id: '/pessoas',
  path: '/pessoas',
  getParentRoute: () => rootRouteImport,
} as any)
const SaidasIndexRoute = SaidasIndexRouteImport.update({
  id: '/saidas/',
  path: '/saidas/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comites': typeof ComitesRoute
  '/materiais': typeof MateriaisRoute
  '/pessoas': typeof PessoasRoute
  '/saidas/': typeof SaidasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comites': typeof ComitesRoute
  '/materiais': typeof MateriaisRoute
  '/pessoas': typeof PessoasRoute
  '/saidas': typeof SaidasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comites': typeof ComitesRoute
  '/materiais': typeof MateriaisRoute
  '/pessoas': typeof PessoasRoute
  '/saidas/': typeof SaidasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/comites' | '/materiais' | '/pessoas' | '/saidas/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/comites' | '/materiais' | '/pessoas' | '/saidas'
  id: '__root__' | '/' | '/comites' | '/materiais' | '/pessoas' | '/saidas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComitesRoute: typeof ComitesRoute
  MateriaisRoute: typeof MateriaisRoute
  PessoasRoute: typeof PessoasRoute
  SaidasIndexRoute: typeof SaidasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comites': {
      id: '/comites'
      path: '/comites'
      fullPath: '/comites'
      preLoaderRoute: typeof ComitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiais': {
      id: '/materiais'
      path: '/materiais'
      fullPath: '/materiais'
      preLoaderRoute: typeof MateriaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pessoas': {
      id: '/pessoas'
      path: '/pessoas'
      fullPath: '/pessoas'
      preLoaderRoute: typeof PessoasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saidas/': {
      id: '/saidas/'
      path: '/saidas'
      fullPath: '/saidas/'
      preLoaderRoute: typeof SaidasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComitesRoute: ComitesRoute,
  MateriaisRoute: MateriaisRoute,
  PessoasRoute: PessoasRoute,
  SaidasIndexRoute: SaidasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
